server:
  port: 8081
spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false


  h2:
    console:
      enabled: true
      path: /h2-store
    hikari:
      jdbc-url: jdbc:h2:mem:storeDb;MODE=MYSQL

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:storeDb;MODE=MySQL;
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:static/*.sql
      mode: always


logging:
  level:
    org.hibernate.SQL: debug
